#pragma once

#include <process.h>
#include "../Default/framework.h"

namespace Tool_Map
{
	const unsigned int			g_iWinSizeX = 1600;
	const unsigned int			g_iWinSizeY = 900;

	const unsigned int			g_iHalfWinSizeX = 800;
	const unsigned int			g_iHalfWinSizeY = 450;

	enum class LEVEL { STATIC, LOADING, LOGO, VILLAGE, DESERT, BOSS, END };

	enum class MAP_THEME { TUTORIAL, GORILLA, SCARLET, COMMON, END };

	enum class DESERT_THEME { BUILDING_RUIN, ENVIRONMENT, XION, CANYON, END };


	enum class NAVI_MODE { NONE, ADD_POINT, ADD_CELL, DELETE_CELL, RESET_ALL, END };
	enum class TOOL_MODE { MAP, LIGHT, CAMERA, END };
	enum class ADD_OBJECT {
		BAMBOO, REED, ROCK1, ROCK2, ROCK3, ROCK4, ROCK5, ROCK6, ROCK7, ROCK8, CHERRYBLOSSOM1, CHERRYBLOSSOM2, CHERRYBLOSSOM3, CHERRYBLOSSOM4,
		GRASS, DRYGRASS1, DRYGRASS2, DRYGRASS3, MOON,
		CM_ROCK1, CM_ROCK2, CM_ROCK3, CM_ROCK4, CM_ROCK5, CM_ROCK6, CM_ROCK7, CM_ROCK8, CM_ROCK9, CM_ROCK10, CM_ROCK11, CM_ROCK12, CM_ROCK13, CM_ROCK14,

		STONEWALL1, STONEWALL2, STONE1, STONE2, STONE3, STONE4, STAIR, INSCRIPTION_L, INSCRIPTION_R, TOMBSTONE, TOMBSTONEBASE1, TOMBSTONEBASE2,
		STONETILE, GIWAJIP, STONELANTERN1, STONELANTERN2, GIWAJIP2,

		PLAYER,
		TERRAIN_INCREASE_RECT, TERRAIN_DECREASE_RECT, TERRAIN_FLAT, TERRAIN_UP, TERRAIN_DOWN, TERRAIN_HILL, MASK_BLACK, MASK_WHITE, END
	};


	enum class DESESRT_RUIN_OBJECT
	{
		PLAYER = 0,
		DOOR_A, DOOR_B, DOOR_C, DOOR_D, DOOR_E, DOOR_F, DOOR_G, DOOR_H, DOOR_I, DOOR_J, DOOR_N, DOOR_P, DOOR_R,
		FLOOR_A, FLOOR_B, FLOOR_C, FLOOR_D, FLOOR_E, FLOOR_F, FLOOR_G, FLOOR_H, FRAME_A, FRAME_B, RUIN_A, RUIN_B, RUIN_C, RUIN_D,
		RUIN_BUILDING_A, RUIN_BUILDING_B, RUIN_BUILDING_C, STONE009_A, STONE009_B, WALL_A, WALL_B, WALL_C, WALL_D, WALL_E, WALL_F, WALL_G, WALL_H, WALL_I,
		WALL007_A, WALL007_B, WALL007_C, WALL007_D, WALL007_E, WALL007_F, WALL007_G,
		
        CANYON_1A, CANYON_2A, CANYON_3A, CANYON_4A,CANYON_5A,CANYON_6A,CANYON_12A, CANYON_14A, CANYON_14B, CANYON_15A, CANYON_16A, CANYON_16B, CANYON_17A,
		CANYON_17B, CANYON_18A,  CANYON_20A, CANYON_21A, CANYON_22A, CANYON_23A, CANYON_24A, CANYON_35A, CANYON_39A, CANYON_39C, CANYON_39D,
		CANYON_43A, CANYON_44A, CANYON_46A, CANYON_50A, CANYON_52A, CANYON_55A, CANYON_58A, CANYON_59A, CANYON_60A, CANYON_61A, CANYON_65A,
		CANYON_66A, CANYON_67A, CANYON_69A, CANYON_71A, CANYON_80A, CANYON_81A,CANYON_93A, CANYON_95A, CANYON_96A, CANYON_97A, CANYON_98A, CANYON_100A, CANYON_101A, 
		CANYON_103A, CANYON_104A, CANYON_105A,CANYON_106A,CANYON_108A, CANYON_109A, CANYON_110A, CANYON_111A, CANYON_112A, CANYON_113A,  CANYON_115A,  CANYON_116A, CANYON_117A, CANYON_121A, 
		CANYON_122A, CANYON_123A, CANYON_125A, CANYON_126A, CANYON_127A, CANYON_127B, CANYON_127C, CANYON_127D, CANYON_127E, CANYON_128A,
		CANYON_128B, CANYON_128C, CANYON_131A,CANYON_132A,CANYON_132B,CANYON_132C,CANYON_133B,
		TERRAIN_INCREASE_RECT, TERRAIN_DECREASE_RECT, TERRAIN_FLAT, TERRAIN_UP, TERRAIN_DOWN, TERRAIN_HILL, MASK_BLACK, MASK_WHITE, 
		
		XION_BUILDING,
		
		END
	};

	typedef struct RuinComponentDesc
	{
		const wchar_t* pComponentTag;

	}RuinComponentDesc;
}

using namespace Tool_Map;

extern HINSTANCE	g_hInstance;
extern HWND			g_hWnd;
extern bool		g_bIsImgKeyBoardFoucs;